# Generated by Django 5.1.3 on 2024-11-26 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('father_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.CharField(blank=True, max_length=1024, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('pincode', models.CharField(blank=True, max_length=254, null=True)),
                ('is_aadhar_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_settings.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_settings.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('accused_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('victim_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(blank=True, max_length=1024, null=True)),
                ('priority', models.CharField(blank=True, max_length=1024, null=True)),
                ('grievance_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('previous_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_time', models.TimeField(blank=True, null=True)),
                ('prosecutor_lawyer', models.CharField(blank=True, max_length=1024, null=True)),
                ('defender_lawyer', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accused', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievance_accused', to='customer.customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievance_employee', to='admin_settings.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievance_user', to=settings.AUTH_USER_MODEL)),
                ('victim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievance_victim', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
