# Generated by Django 5.1.3 on 2024-11-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='permissionsets',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='permissionsets',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='permissionsets',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permission_set',
        ),
        migrations.DeleteModel(
            name='EmployeePermissions',
        ),
        migrations.DeleteModel(
            name='PermissionSets',
        ),
    ]
